# Generated by Django 3.2 on 2021-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(max_length=100)),
                ('entry_body', models.TextField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
